language: php
php:
  - '5.6'
  - '7.0'
  - 'hhvm'

before_script:
   - composer install

script: phpunit --coverage-clover=coverage.clover

notifications:
  email: false
  irc:
    channels:
       secure: "U/U9R4Eq03gDiwVZiEikzu/ZAz3hb3rLsYqeBJ1gZDllbbnntu54Ov+xuRUQGNIG23WtkD9kOFwKUNvAKlduk85m9yqGAQXeyXEG+nGHLLypmS1FYRDHgjzxMaijPqSKWZ0T1l3YgEqJhuEjnL7WW3MWYhvk+ad4rtlH+4T6CBQ="
    on_success: change
    on_failure: always

after_script:
    - wget https://scrutinizer-ci.com/ocular.phar
    - php ocular.phar code-coverage:upload --format=php-clover coverage.clover


sudo: false
